---
kind: pipeline
name: mirror the github
steps:
  - name: push to mirror
    image: appleboy/drone-git-push
    settings:
      branch: master
      remote: ssh://git@github.com/mlunax/Dockerfiles.git
      ssh_key:
        from_secret: ssh_key
      commit: false
trigger:
  ref:
    - refs/heads/master
